[workspace]
resolver = "2"
members = [
    "utils",
    "aoc_derive", "day1",
]

[workspace.dependencies]
itertools = "0.12.0"
ndarray = "0.15.6"
num = "0.4.1"
parse-display = "0.8.2"
priority-queue = "1.3.2"
rayon = "1.8.0"
regex = "1.10.2"
